spring:
  cloud:
    gateway:
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/*/hosp/**

        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**
      discovery:
        locator:
          enabled: true
  application:
    name: yygh-gateway